wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1709082872.556992
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.13.10
      8:
      - 5
architecture:
  desc: null
  value: efficientnet_b0
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 10
